### ISSUE TITLE
Increase contrast on printable gifts

### ISSUE THREAD

**Issue by maplesyrupsucker** [Bitcoin-com/gifts-frontend#18]
Scanning for funds via jpg often fails on some of the designs: 

- Green fails
- Orange works
- Easy print works

Recommending we upgrade and match consistency to wallet designs

![image](https://user-images.githubusercontent.com/3764321/80180133-44d95c00-862c-11ea-931c-10ee614fd123.png)

I suggest keeping the footer part from the current design for the steps (download wallet > settings > sweep paper wallet)

![image](https://user-images.githubusercontent.com/3764321/80180201-663a4800-862c-11ea-9502-f36ea319ea94.png)

**Comment by josephroyking** [comment]
https://github.com/Bitcoin-com/gifts-frontend/pull/19

One issue: this new QR code implementation does not show up in the jpg exports, though this probably makes them easier to scan.

**Comment by josephroyking** [comment]
Deployed at gifts.bitcoin.com
